<?php

namespace Tests\Feature;

use App\Eloquent\EloquentRecruitment;
use App\Eloquent\EloquentUser;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class EditEventTest extends TestCase
{
    use RefreshDatabase;

    /** @var EloquentUser $user */
    private $user;

    /** @var EloquentRecruitment */
    private $recruitment;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->setInitData();
        $this->user        = $this->login();
        $this->recruitment = factory(EloquentRecruitment::class)->create([
            'create_id' => $this->user->id,
        ]);
    }

    public function testCanDisplayEditRecruitmentForm()
    {
        $this->get("/my-page/manage/event/edit/{$this->recruitment->id}")
             ->assertStatus(200)
             ->assertViewIs('manage.edit_event.form');
    }

//    public function testCanDisplayCreatedRecruitmentInfoInEditForm()
//    {
//
//    }
}
